"""Place a 3D asset made somewhere else (e.g. generated by an image-to-3D model) on the mat.

A generated asset lives in its model's own frame - its own up axis, facing, unit and origin. We know
exactly where our cameras were and what the object looks like from each of them (the SAM 2 masks),
so we search for the similarity transform (up axis, yaw, scale, position on the mat) whose rendered
silhouettes best match those masks. That also restores real-world scale, which generators lose.

Search: the asset is first stood on the mat (bottom at z = 0, centred), then every up axis (6),
yaw (15 deg steps) and size (log-spaced) is scored by mean silhouette IoU over the photos, and the
best is refined locally, also in x/y. Rendering uses gsplat, so this needs a CUDA GPU.
"""

from __future__ import annotations

import itertools
from dataclasses import dataclass

import numpy as np

from .splat import GaussianCloud, transformed

UP_AXES = {  # rotation taking the named axis of the asset to +Z
    "+z": np.eye(3),
    "-z": np.diag([1.0, -1.0, -1.0]),
    "+y": np.array([[1.0, 0, 0], [0, 0, -1], [0, 1, 0]]),
    "-y": np.array([[1.0, 0, 0], [0, 0, 1], [0, -1, 0]]),
    "+x": np.array([[0, 0, -1.0], [0, 1, 0], [1, 0, 0]]),
    "-x": np.array([[0, 0, 1.0], [0, 1, 0], [-1, 0, 0]]),
}


@dataclass
class Silhouette:
    viewmat: np.ndarray  # (4, 4) world -> camera
    K: np.ndarray  # (3, 3) pinhole
    mask: np.ndarray  # (H, W) bool, the object


@dataclass
class Fit:
    up: str
    yaw_deg: float
    size_m: float  # longest horizontal extent after scaling
    offset_m: tuple[float, float]
    iou: float
    R: np.ndarray
    scale: float
    t: np.ndarray


def _yaw(deg: float) -> np.ndarray:
    c, s = np.cos(np.radians(deg)), np.sin(np.radians(deg))
    return np.array([[c, -s, 0.0], [s, c, 0.0], [0.0, 0.0, 1.0]])


def _stand(means: np.ndarray, U: np.ndarray) -> tuple[np.ndarray, float]:
    """Translation that puts the rotated asset on the mat, centred; and its horizontal extent."""
    p = means @ U.T
    lo, hi = np.percentile(p, [1, 99], axis=0)
    centre = np.array([(lo[0] + hi[0]) / 2, (lo[1] + hi[1]) / 2, lo[2]])
    return -centre, float(max(hi[0] - lo[0], hi[1] - lo[1]))


def fit_to_silhouettes(cloud: GaussianCloud, views: list[Silhouette], device: str = "cuda",
                       sizes_m=(0.03, 0.30), yaw_step: float = 15.0) -> Fit:
    import torch
    from gsplat import rasterization

    h, w = views[0].mask.shape
    viewmats = torch.tensor(np.stack([v.viewmat for v in views]), dtype=torch.float32, device=device)
    Ks = torch.tensor(np.stack([v.K for v in views]), dtype=torch.float32, device=device)
    target = torch.tensor(np.stack([v.mask for v in views]), dtype=torch.bool, device=device)
    base = torch.tensor(cloud.means, dtype=torch.float32, device=device)
    quats = torch.tensor(cloud.quats, dtype=torch.float32, device=device)
    log_s = torch.tensor(cloud.scales, dtype=torch.float32, device=device)
    alpha = torch.sigmoid(torch.tensor(cloud.opacities, dtype=torch.float32, device=device))
    white = torch.ones((len(base), 3), device=device)

    def score(R: np.ndarray, s: float, t: np.ndarray) -> float:
        Rt = torch.tensor(R, dtype=torch.float32, device=device)
        means = s * base @ Rt.T + torch.tensor(t, dtype=torch.float32, device=device)
        # Quaternion rotation is irrelevant for silhouettes at this resolution; scale is not.
        with torch.no_grad():
            _, a, _ = rasterization(means, quats, torch.exp(log_s) * s, alpha, white, viewmats, Ks, w, h,
                                    packed=False)
        pred = a[..., 0] > 0.5
        inter = (pred & target).sum(dim=(1, 2)).float()
        union = (pred | target).sum(dim=(1, 2)).float().clamp(min=1)
        return float((inter / union).mean())

    best = None
    for up, U in UP_AXES.items():
        stand, extent = _stand(cloud.means, U)
        for size in np.geomspace(*sizes_m, 14):
            s = size / max(extent, 1e-9)
            for yaw in np.arange(0.0, 360.0, yaw_step):
                R = _yaw(yaw) @ U
                t = s * (_yaw(yaw) @ stand)
                iou = score(R, s, t)
                if best is None or iou > best[0]:
                    best = (iou, up, yaw, size, (0.0, 0.0))

    # Local refinement around the winner: yaw, size and position on the mat.
    iou, up, yaw, size, off = best
    U = UP_AXES[up]
    stand, extent = _stand(cloud.means, U)
    for step_yaw, step_size, step_xy in ((5.0, 0.06, 0.004), (1.5, 0.02, 0.0015)):
        for dy, ds, dx, dyy in itertools.product((-step_yaw, 0, step_yaw), (-step_size, 0, step_size),
                                                 (-step_xy, 0, step_xy), (-step_xy, 0, step_xy)):
            y2, sz2, off2 = yaw + dy, size * (1 + ds), (off[0] + dx, off[1] + dyy)
            s = sz2 / max(extent, 1e-9)
            R = _yaw(y2) @ U
            t = s * (_yaw(y2) @ stand) + np.array([off2[0], off2[1], 0.0])
            cand = score(R, s, t)
            if cand > iou:
                iou, yaw, size, off = cand, y2, sz2, off2

    s = size / max(extent, 1e-9)
    R = _yaw(yaw) @ U
    t = s * (_yaw(yaw) @ stand) + np.array([off[0], off[1], 0.0])
    return Fit(up, float(yaw % 360), float(size), (float(off[0]), float(off[1])), float(iou), R, float(s), t)


def apply(cloud: GaussianCloud, fit: Fit) -> GaussianCloud:
    return transformed(cloud, fit.R, fit.scale, fit.t)
